### ISSUE TITLE
Couldn't find any versions for "url-slug" that matches "^3.0.3"

### ISSUE THREAD

**Issue by 5idu** [stldo/url-slug#20]
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/26264096/154202740-ccaa3a16-c821-4200-bb33-41a0c8803a81.png">

the latest version is "3.0.2"!

**Comment by stldo** [comment]
Sorry, I didn't understand your issue. Are you having issues to install version 3.0.3? Try clearing the npm cache, it should help. Version 3.0.3 is published, and it's working fine on my side. Please let me know if you're still having issues.

**Comment by 5idu** [comment]
> Sorry, I didn't understand your issue. Are you having issues to install version 3.0.3? Try clearing the npm cache, it should help. Version 3.0.3 is published, and it's working fine on my side. Please let me know if you're still having issues.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/26264096/154446922-c1b96d4a-21f2-4033-9b7b-6beab4e0a605.png">
can not found version 3.0.3!

**Comment by stldo** [comment]
It doesn't seem to be an issue with url-slug. Try to install using `npm install url-slug@3.0.3`. If that doesn't work, it could be an issue with npm. I found some info about your issue on the following pages:

https://npm.community/t/npm-view-npm-install-cant-find-latest-package-version/1590.html
https://stackoverflow.com/questions/49646887/npm-doesnt-see-the-newest-npm-package-version

If you can't find a solution, I suggest opening an issue in https://github.com/npm/cli repository. I'll close this issue since it isn't related to url-slug.
