### ISSUE TITLE
size

### ISSUE THREAD

**Issue by st0ffern** [stldo/url-slug#9]
How come this library is 314K big?
Could it be that it usese unidecode and that is so big?
It is huge in comparison to what it does.

**Comment by stldo** [comment]
Yes, it's because unidecode. This library was originally created to be used on server side. I'm working on the next version, it'll be optimized for browser usage and will be much smaller.

**Comment by greghuc** [comment]
+1 on reducing size for url-slug. I was surprised to discover that 1/3 of a browser-side js file was unidecode, pulled in by url-slug! (found using source-map-explorer). Thanks for a nice library.

**Comment by stldo** [comment]
If you need to use it browser-side, you can try the latest beta version, 3.0.0-beta.0. It uses String.normalize instead unidecode. I'm still working on unorm support as a polyfill for older browsers and some other things, but it's passing almost all tests from v2.3. I'm using it on production for some weeks in a Node.js implementation and it seems to be working ok. If you need a lightweight module, I invite you to try it!

**Comment by greghuc** [comment]
@stldo so I just switched to url-slug 3.0.0-beta.0 and it's working fine, barring one issue:

urlSlug.revert(decodeURIComponent(urlPart), { camelCase: true, separator: null });
is throwing exception of "separator must be a string".

I solved it by switching to urlSlug.revert(decodeURIComponent(urlPart), { camelCase: true });

I'm wanting to revert "everything": both camel-case and all possible separator characters.

Since "separator: null" is suggested by the README, it might be worth the docs if this doesn't work any more.

Sizewise, things are much better using url-slug 3.0.0-beta.0. My browser-size js file is now 35% smaller.

Many thanks for progressing this :-)

**Comment by stldo** [comment]
Thanks for pointing it! I've fixed this error and also updated the README. These changes will be updated on 3.0.0-beta.1.

**Comment by stldo** [comment]
Just released 3.0.0-beta.3, it's much smaller than previous versions and is compatible with Node.js and most modern browsers. I'm still working on better browser compatibility and implementing more options in v3, so the size should increase a little — right now, the minified bundle has 1.6kB, 765B gzipped. I'm closing this issue as it's resolved.
